import { Navbar } from '@/components/Navbar';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import 'swiper/swiper-bundle.css';
import '@/styles/globals.css';
import { Footer } from '@/components/Footer';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ThunMov - Online Movies & TV Shows',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-black/95 ${inter.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
